/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf --transform 
Files: scene.gltf [71.52KB] > C:\Users\Drews\Downloads\low-poly_f16\scene-transformed.glb [38.9KB] (46%)
Author: SiTitan (https://sketchfab.com/SiTitan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-f16-857c52e25ef146ec9da08a1f3c7706f2
Title: Low-poly F16
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function JetModel(props: any) {
  const { nodes, materials }: any = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} position={[0, 0.881, 1.87]} rotation={[-1.614, 0, 0]} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.material_1} position={[0, 0.955, 0.495]} rotation={[-0.087, 0, 0]} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.material_2} position={[0, 0.955, 0.495]} rotation={[-0.087, 0, 0]} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.material_3} position={[0, 0.955, 0.495]} rotation={[-0.087, 0, 0]} />
      <mesh geometry={nodes.Object_85.geometry} material={materials.material_4} />
      <mesh geometry={nodes.Object_88.geometry} material={materials.material_5} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.material_6} position={[0, 1.108, -0.003]} rotation={[Math.PI / 9, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
