/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf -t --transform 
Files: scene.gltf [1.31MB] > C:\Users\Drews\Downloads\cartoon_low_poly_world_map (2)\scene-transformed.glb [828.06KB] (37%)
Author: antonmoek (https://sketchfab.com/antonmoek)
License: SKETCHFAB Editorial (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/cartoon-low-poly-world-map-e87fa1e143f84348a915b7fe1376d957
Title: Cartoon Low Poly World Map
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Clouds_2_Clouds_0: THREE.Mesh
    Gull_World_ap_0: THREE.Mesh
    Water_2_Water_0: THREE.Mesh
    Gull_3_World_ap_0: THREE.Mesh
    Gull_12_World_ap_0: THREE.Mesh
    Australi_trees_17_World_ap_0: THREE.Mesh
    Australi_trees_25_World_ap_0: THREE.Mesh
    Australi_trees_31_World_ap_0: THREE.Mesh
    Palm_5_World_ap_0: THREE.Mesh
    Palm_9_World_ap_0: THREE.Mesh
    Palm_19_World_ap_0: THREE.Mesh
    Palm_41_World_ap_0: THREE.Mesh
    Palm_64_World_ap_0: THREE.Mesh
    Palm_71_World_ap_0: THREE.Mesh
    Palm_92_World_ap_0: THREE.Mesh
    Palm_97_World_ap_0: THREE.Mesh
    Palm_116_World_ap_0: THREE.Mesh
    House_7_11_World_ap_0: THREE.Mesh
    House_7_3_World_ap_0: THREE.Mesh
    House_7_20_World_ap_0: THREE.Mesh
    House_7_10_2_World_ap_0: THREE.Mesh
    House_7_2_5_World_ap_0: THREE.Mesh
    House_7_11_8_World_ap_0: THREE.Mesh
    House_7_6_9_World_ap_0: THREE.Mesh
    House_7_11_11_World_ap_0: THREE.Mesh
    House_7_11_14_World_ap_0: THREE.Mesh
    House_7_14_6_World_ap_0: THREE.Mesh
    House_7_11_18_World_ap_0: THREE.Mesh
    House_7_3_19_World_ap_0: THREE.Mesh
    House_7_1_15_World_ap_0: THREE.Mesh
    House_7_7_14_World_ap_0: THREE.Mesh
  }
  materials: {
    Clouds: THREE.MeshStandardMaterial
    World_ap: THREE.MeshStandardMaterial
    Water: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function WorldModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials }: any = useGLTF('/world/scene-transformed.glb') as GLTFResult
  return (
      <group {...props} dispose={null}>
      <mesh geometry={nodes.Clouds_2_Clouds_0.geometry} material={materials.Clouds} position={[-0.233, 0.233, 0.038]} scale={0} />
      <mesh geometry={nodes.Gull_World_ap_0.geometry} material={materials.World_ap} position={[-0.123, 0.134, -0.079]} rotation={[0, 0.084, 0]} scale={0} />
      <mesh geometry={nodes.Water_2_Water_0.geometry} material={materials.Water} position={[-0.064, -0.015, -0.074]} scale={0} />
      <instancedMesh args={[nodes.Gull_3_World_ap_0.geometry, materials.World_ap, 8]} instanceMatrix={nodes.Gull_3_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.Gull_12_World_ap_0.geometry, materials.World_ap, 7]} instanceMatrix={nodes.Gull_12_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.Australi_trees_17_World_ap_0.geometry, materials.World_ap, 5]} instanceMatrix={nodes.Australi_trees_17_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.Australi_trees_25_World_ap_0.geometry, materials.World_ap, 5]} instanceMatrix={nodes.Australi_trees_25_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.Australi_trees_31_World_ap_0.geometry, materials.World_ap, 5]} instanceMatrix={nodes.Australi_trees_31_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.Palm_5_World_ap_0.geometry, materials.World_ap, 27]} instanceMatrix={nodes.Palm_5_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.Palm_9_World_ap_0.geometry, materials.World_ap, 7]} instanceMatrix={nodes.Palm_9_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.Palm_19_World_ap_0.geometry, materials.World_ap, 17]} instanceMatrix={nodes.Palm_19_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.Palm_41_World_ap_0.geometry, materials.World_ap, 7]} instanceMatrix={nodes.Palm_41_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.Palm_64_World_ap_0.geometry, materials.World_ap, 5]} instanceMatrix={nodes.Palm_64_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.Palm_71_World_ap_0.geometry, materials.World_ap, 5]} instanceMatrix={nodes.Palm_71_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.Palm_92_World_ap_0.geometry, materials.World_ap, 16]} instanceMatrix={nodes.Palm_92_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.Palm_97_World_ap_0.geometry, materials.World_ap, 27]} instanceMatrix={nodes.Palm_97_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.Palm_116_World_ap_0.geometry, materials.World_ap, 5]} instanceMatrix={nodes.Palm_116_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.House_7_11_World_ap_0.geometry, materials.World_ap, 16]} instanceMatrix={nodes.House_7_11_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.House_7_3_World_ap_0.geometry, materials.World_ap, 9]} instanceMatrix={nodes.House_7_3_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.House_7_20_World_ap_0.geometry, materials.World_ap, 7]} instanceMatrix={nodes.House_7_20_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.House_7_10_2_World_ap_0.geometry, materials.World_ap, 6]} instanceMatrix={nodes.House_7_10_2_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.House_7_2_5_World_ap_0.geometry, materials.World_ap, 18]} instanceMatrix={nodes.House_7_2_5_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.House_7_11_8_World_ap_0.geometry, materials.World_ap, 14]} instanceMatrix={nodes.House_7_11_8_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.House_7_6_9_World_ap_0.geometry, materials.World_ap, 22]} instanceMatrix={nodes.House_7_6_9_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.House_7_11_11_World_ap_0.geometry, materials.World_ap, 8]} instanceMatrix={nodes.House_7_11_11_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.House_7_11_14_World_ap_0.geometry, materials.World_ap, 12]} instanceMatrix={nodes.House_7_11_14_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.House_7_14_6_World_ap_0.geometry, materials.World_ap, 5]} instanceMatrix={nodes.House_7_14_6_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.House_7_11_18_World_ap_0.geometry, materials.World_ap, 8]} instanceMatrix={nodes.House_7_11_18_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.House_7_3_19_World_ap_0.geometry, materials.World_ap, 7]} instanceMatrix={nodes.House_7_3_19_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.House_7_1_15_World_ap_0.geometry, materials.World_ap, 5]} instanceMatrix={nodes.House_7_1_15_World_ap_0.instanceMatrix} />
      <instancedMesh args={[nodes.House_7_7_14_World_ap_0.geometry, materials.World_ap, 7]} instanceMatrix={nodes.House_7_7_14_World_ap_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/world/scene-transformed.glb')
